### ISSUE TITLE
Any way for an Enum to inherit from another Enum?

### ISSUE THREAD

**Issue by meddulla** [lloydmeta/enumeratum#120]
Hi,

I have some enum values that are common to several enums. 
How would I reuse the basegroup in GroupA so that it had metricA, metricB, etc?

Not sure if this is possible but I might be missing something. 
```
import enumeratum._
import enumeratum.EnumEntry

sealed trait BaseGroup extends EnumEntry
object BaseGroup extends Enum[BaseGroup] {
  val values = findValues
  case object metricA extends BaseGroup
  case object metricB extends BaseGroup
  case object metricC extends BaseGroup

}
// simple inheritance doesn't seem to work
sealed trait GroupA extends EnumEntry
object GroupA extends Enum[GroupA] {
  val values = findValues
  case object metricD extends GroupA
  case object metricE extends GroupA

}

// How do I get it to be
// Vector(metricA, metricB, metricC, metricD, metricE)
// or sum both Base and GroupA
GroupA.values
```

Is there a way to do it? Thanks a lot!

**Comment by lloydmeta** [comment]
Hi there,

There's nothing automatic that will do it for you sadly; the macro literally only searches the body it's in at the level that it's in (doesn't search deeper). This is what I think could work, but I understand it might not appeal to you because of the manual concatenation:

(Please excuse the use of Ammonite)

```scala
@ import $ivy.`com.beachape::enumeratum:1.5.7`, enumeratum._ 
import $ivy.$                               , enumeratum._
@ {
sealed trait BaseGroup extends EnumEntry
object BaseGroup extends Enum[BaseGroup] {
  // Manually concatenate
  val values = findValues ++ GroupA.values
  case object metricA extends BaseGroup
  case object metricB extends BaseGroup
  case object metricC extends BaseGroup
}

sealed trait GroupA extends BaseGroup
object GroupA extends Enum[GroupA] {
  val values = findValues
  case object metricD extends GroupA
  case object metricE extends GroupA
}
}

@ BaseGroup.values 
res2: collection.immutable.IndexedSeq[BaseGroup] = Vector(metricA, metricB, metricC, metricD, metricE)
```

**Comment by meddulla** [comment]
The idea was actually the other way round, that there would be a GroupA, GroupB, etc that would all get the common metrics from the BaseGroup, and not that BaseGroup would have them all. But either way, yeah, was hoping that something better would be possible. Anyway, thanks for your input.

**Comment by lloydmeta** [comment]
I see. I can kind of see what you're trying to do, but that doesn't make much sense from a type-perspective; you would end up having `values` in the enum "subtypes" that have a less precise type of `IndexedSeq[BaseGroup]` as opposed to their more precise group (e.g. `IndexedSeq[GroupA]`, `IndexedSeq[GroupB]`).

Given this type-level dilemma,  it might be that enums aren't the right tool to solve the problem you have :)
