### ISSUE TITLE
Missing EnumValues in IntEnumEntry

### ISSUE THREAD

**Issue by zeromancer** [lloydmeta/enumeratum#138]
In my own code i got a NullPointerException -> before i noticed that some values in IntEnumEntry do not get initialized.
* Am I doing something wrong ?
* Or is this intended behavior ?

In the following example:
* rightS seems to to be initialized just fine
* while leftS -> is null

Reproducible code:

```
import enumeratum.values.{IntEnum, IntEnumEntry}
import scala.collection.immutable.IndexedSeq

sealed abstract class CPT(val value: Int, val leftS: CPT, val rightS: CPT) extends IntEnumEntry {
	val left = Option(leftS)
	val right = Option(rightS)
}

case object CPT extends IntEnum[CPT] {
	val values: IndexedSeq[CPT] = findValues

	case object S extends CPT(0, leftS = null, rightS = D)

	case object H extends CPT(1, leftS = null, rightS = null)

	case object D extends CPT(2, leftS = S, rightS = null)

}
```

```
import org.scalatest.FunSuite
import scala.collection.immutable

class TestExample extends FunSuite {

	test("test") {
		assert(CPT.S.right.contains(CPT.D))
		assert(CPT.D.left.contains(CPT.S))
	}
}
```

error message:
> None did not contain S
ScalaTestFailureLocation: game.TestExample at (TestExample.scala:10)
org.scalatest.exceptions.TestFailedException: None did not contain S
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)

**Comment by lloydmeta** [comment]
I think there's a circular dependency between S and D here; `S.rightS` points to D, but `D.leftS` points to S.

Here's a minimal repro using Ammonite that does not involve enumeratum at all:

```scala
@ {
  sealed abstract class Klass(val sib: Klass)
  case object A extends Klass(B)
  case object B extends Klass(A)
  } 
defined class Klass
defined object A
defined object B
@ A.sib 
res1: Klass = B
@ B.sib 
res2: Klass = null
```

To make this work, you'd have to try to get rid of the circular dependency or use tricks like this:

```scala
@ {
  // Make the constructor argument a private call-by-name param
  sealed abstract class Klass(buildSib: => Klass) {
    lazy val sib = buildSib // <-- cache the sib
  }
  case object A extends Klass(B)
  case object B extends Klass(A)
  } 
defined class Klass
defined object A
defined object B
@ A.sib 
res4: Klass = B
@ B.sib 
res5: Klass = A
```

**Comment by zeromancer** [comment]
ok, I found a solution (does not look as elegant, but at least works):
* put default Method in abstract class
* overwrite this method in case objects themselves
