### ISSUE TITLE
Find Value by Annotation

### ISSUE THREAD

**Issue by bertderbecker** [lloydmeta/enumeratum#147]
Hey!

Nice project!
I would like to have a bit of syntactic sugar: it would be nice to select the value field by an annotation to avoid the overhead of overriding the `value` method. Here is an example:

```
sealed abstract class Code(@Value val value: Int, val door: String) extends IntEnumEntry
```
Is it realizable?

**Comment by lloydmeta** [comment]
Can you expand a little bit on what you mean by avoiding the overhead of overriding value? [Current usage](https://github.com/lloydmeta/enumeratum#valueenum) looks quite similar to what you've got there.

```scala
sealed abstract class LibraryItem(val value: Int, val name: String) extends IntEnumEntry
```

**Comment by bertderbecker** [comment]
Currently, i have to override the method `value` like
```
sealed abstract class LibraryItem(val value: Int, val name: String) extends IntEnumEntry {
  override def value: Int = code
}
```

What I propose is a macro annotation for the parameter:
```
sealed abstract class Code(@Value val value: Int, val door: String) extends IntEnumEntry
```
Here it's not necessary to override the `value` method...

**Comment by lloydmeta** [comment]
> Currently, i have to override the method `value`:
> ```
> sealed abstract class LibraryItem(val value: Int, val name: String) extends IntEnumEntry {
>   override def value: Int = code
> }
> ```
> 
> What I propose is a macro annotation for the parameter:
> ```
> sealed abstract class Code(@Value val value: Int, val door: String) extends IntEnumEntry
> ```
> Here it's not necessary to override the `value` method...
> 

Just to make sure I understand fully what you mean, you probably have this situation right now:

```scala
sealed abstract class LibraryItem(val code: Int, val name: String) extends IntEnumEntry {
  override def value: Int = code
}
```
and what you want is
```scala
sealed abstract class Code(@Value val code: Int, val door: String) extends IntEnumEntry
```
?

**Comment by bertderbecker** [comment]
Exactly! :)

**Comment by lloydmeta** [comment]
I think it's do-able, but maybe it's a nice-to-have. Also, I don't think there's going to be much actual runtime performance overhead to the alias method once JIT kicks in. 

If you would like to contribute this feature, please feel free to give it a try :) My only request is that it be done without adding dependencies and that error cases be handled nicely !
