### ISSUE TITLE
Update Maven Badge for enumeratum-play-json

### ISSUE THREAD

**Issue by AndrewZurn** [lloydmeta/enumeratum#148]
Hey there,

It looks like 1.5.12 is currently available on maven central, but the badge on the project for play-json is still on the 1.5.12-2.6.0-M7 milestone release version. Might be nice to have it updated for other's to use without having to check if the actual release if available. :)

Thanks,
Andrew

**Comment by lloydmeta** [comment]
Hi,

Thanks for checking out the project and for pointing that out :). Unfortunately, I'm not sure what we can do here: that badge is autogenerated from maven-badges and I think the milestone releases' naming might have thrown their logic off. I think it'll be fixed when we hit 1.5.13 though.

If you have any ideas, please let me know

Lloyd

**Comment by AndrewZurn** [comment]
That works! Will keep my fingers crossed that the bump to 1.5.13 does the trick.
