### ISSUE TITLE
Feature request: Enum.materializeEnum for generic T <: EnumEntry

### ISSUE THREAD

**Issue by danxmoran** [lloydmeta/enumeratum#149]
Given:
```scala
import enumeratum.{Enum, EnumEntry}

class EntryGetter[T <: EnumEntry] {
  def getEntry(name: String): T = Enum.materializeEnum[T].withName(name)
}
```
I get the error `Could not find the companion object for type type T.`

I'm new to macros / reflection in Scala so for all I know it might not be possible to pull off, but it'd be awesome if this sort of generic lookup could work. My use-case is that I was trying to build a generic `EnumEntry` parser for use with [case-app](https://github.com/alexarchambault/case-app).

**Comment by lloydmeta** [comment]
Since `Enum.materializeEnum` is declared on the companion object of `Enum`, it is basically available everywhere as long as you grab it implicitly, one way or another.

For example, the following works in Ammonite:

```scala
import enumeratum.{Enum, EnumEntry}

// Here we introduce a context bound on T
class EntryGetter[T <: EnumEntry: Enum] {
  // materialise the Enum[T] and bind it (available via Enum.materializeEnum)
  private val enumCompanion = implicitly[Enum[T]]
  def getEntry(name: String): T = enumCompanion.withName(name)
}

sealed trait Light extends EnumEntry

object Light extends Enum[Light] {
  val values = findValues
  case object Red extends Light
  case object Yellow extends Light
  case object Green extends Light
}

val getter = new EntryGetter[Light]

println(getter.getEntry("Red"))
```

[Ammonite usage](https://gist.github.com/lloydmeta/256b46847d4b687ff69f341b5e69149b)

**Comment by lloydmeta** [comment]
I'll close this issue for now; feel free to re-open if needed.
