### ISSUE TITLE
Name clash with Play for 'Json'

### ISSUE THREAD

**Issue by howyp** [lloydmeta/enumeratum#15]
Thanks for the library, really useful.

Something that I've noticed is that the suggested way of importing enumeratum introduces a name clash with Play:

```scala
scala> def test() = {
     |   import enumeratum._
     |   import play.api.libs.json._
     |   Json.toJson("test")
     | }
<console>:19: error: reference to Json is ambiguous;
it is imported twice in the same scope by
import play.api.libs.json._
and import enumeratum._
         Json.toJson("test")
```

This can be worked around, but given that enumeratum is specifically designed to work well with Play's json support, this seemed a bit of a shame to me. Could we rename the `enumeratum.Json` object?

**Comment by lloydmeta** [comment]
Oh, nice find. This is a pity. I'm thinking of `enumeratum.JsonHelper` as a name but am open to suggestions :)

**Comment by howyp** [comment]
`enumeratum.EnumFormats` would seem most descriptive to me?

**Comment by lloydmeta** [comment]
@howyp done via #16 with release 1.3.0
