### ISSUE TITLE
LowerCamelcase doesn't work

### ISSUE THREAD

**Issue by 1gnition** [lloydmeta/enumeratum#151]
I'm using version `"com.beachape" %% "enumeratum" % "1.5.12"` with Scala 2.12, and LowerCamelcase prints the names with everything lowercase, no capitals at all.

Given the following example, I would expect `howAreYou` to be printed, but what's printed is `howareyou`:

```scala
import enumeratum.{Enum, EnumEntry}
import enumeratum.EnumEntry.LowerCamelcase

import scala.collection.immutable.IndexedSeq

sealed trait Thing extends EnumEntry with LowerCamelcase
object Thing extends Enum[Thing] {
  val values: IndexedSeq[Thing] = findValues
  case object HowAreYou extends Thing

}

println(Thing.HowAreYou.entryName)
```

**Comment by lloydmeta** [comment]
Hi there,

Thanks for taking a look at enumeratum and filing this issue.

Things get a bit tricky with the different stackable modifiers here, but I believe this is how it was intended to be used:

https://github.com/lloydmeta/enumeratum/blob/e42b8d9d19b8aeff0c34d3f5066e5ec5e93235f1/enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala#L312

That trait was contributed by @dmit, so if you'd like to see it changed, maybe we should all discuss further :)

**Comment by dmit** [comment]
Yep, `LowerCamelCase` was only meant to be used with `snake_case`-formatted enums, since it builds on `CamelCase`.

@1gnition, I think the `Uncapitalised` trait should do what you need in that example.

**Comment by 1gnition** [comment]
Thanks guys. `Uncapitalised` does the job

**Comment by lukaszlenart** [comment]
I was hit by the same issue and using `Uncapitalised` did the job. Anyway I think you should change description of that class which is misleading now:

```
  /**
    * Stackable trait to convert the entryName to lowerCamelCase.
    */
```

It clear says that `entryName` will represented as a `camelCase` and there is no information that it works only with `*_*` pattern.

And the `LowerCamelcase` can be easily fixed:

```scala
trait LowerCaseValue extends EnumEntry {

  private val regexp1: Pattern    = Pattern.compile("([A-Z]+)([A-Z][a-z])")
  private val regexp2: Pattern    = Pattern.compile("([a-z\\d])([A-Z])")
  private val replacement: String = "$1_$2"

  private def camel2WordArray(name: String): Array[String] = {
    val first = regexp1.matcher(name).replaceAll(replacement)
    regexp2.matcher(first).replaceAll(replacement).split("_")
  }

  private[this] def toCamelCase(value: String): String = {
    if (value.isEmpty) {
      value
    } else {
      val words = camel2WordArray(value)
      words.toList match {
        case Nil =>
          value

        case head :: Nil =>
          head.toLowerCase

        case head :: tail =>
          head.toLowerCase + tail.mkString
      }
    }
  }

  private[this] lazy val stableEntryName: String = toCamelCase(super.entryName)

  override def entryName: String = stableEntryName
}
```

**Comment by dmit** [comment]
@lukaszlenart Yes, unfortunately the current set of stackable traits are not truly orthogonal. There's a bunch of corner cases to consider due to the number of different enum formats that this library supports. For example, the proposed code above doesn't handle `snake_case`, `UPPER_CASE`, `kebab-case`, `dot.case` etc correctly.

I'll leave it up to @lloydmeta to decide whether this is a documentation issue or if Enumeratum should strive to make sure that each case is convertible to every other case.

**Comment by lloydmeta** [comment]
I've given it some thought and I think that trying to make all of these stackable traits work with each other 100% of the time is going to be a very nasty exercise.  Inheritance is a pretty poor way of composing behaviour to begin with IMO (though convenient!); and you're bound to find some corner cases here and there.

My thinking is that we should improve the documentation and call it a day.
