### ISSUE TITLE
Unable to load enumeratum-circe with sbt 1.0.3 or 1.0.5

### ISSUE THREAD

**Issue by akauppi** [lloydmeta/enumeratum#156]
I think this is an sbt issue, and I filed an issue there: [#3741](https://github.com/sbt/sbt/issues/3741)

However, in case there's something in the way enumeratum-circe is packaged, that causes the problem to get triggered, maybe a solution can be found in this project as well. I have not seen similar with any other libraries I use (also normal enumeratum loads fine).

Git repo for fast trying out the issue: [sbt-bug-enumeratum-circe](http://github.com/akauppi/sbt-bug-enumeratum-circe)

**Comment by lloydmeta** [comment]
Wow. Interesting ! I’m not aware of any way that enumeratum-circe is packaged differently but will have a look when I get my computer back from repair.

**Comment by lloydmeta** [comment]
I just gave your repository a try, but it seems to work fine here. I saw https://github.com/sbt/sbt/issues/3726 and realised I'm still on JDK8. What version do you happen to be on?

**Comment by akauppi** [comment]
This seems to be fixed in 1.1.0, so closing. Using JDK 9.0.4.
