### ISSUE TITLE
Java interop

### ISSUE THREAD

**Issue by martin-g** [lloydmeta/enumeratum#157]
Hi,

I'm having hard time figuring out how to use the enum values from Java code.

My enum looks like:
```scala
object Transfer {

  sealed trait Type extends EnumEntry
  object Type extends Enum[Type] {
    val values: immutable.IndexedSeq[Type] = findValues
    case object DEPOSIT extends Type
    case object WITHDRAWAL extends Type
  }
```

Intellij IDEA seems to be happy with `Transfer.Type.DEPOSIT$.MODULE$` but scalac says: `Error:(415, 89) java: incompatible types: enumeratum.EnumEntry cannot be converted to com.example.Transfer.Type`

Any idea whether this can be achieved somehow ?

Scala: 2.12.4
Intellij IDEA: 2017.3.2
Enumeratum: 1.5.12

**Comment by lloydmeta** [comment]
Hey there,

Thanks for asking this question ! I'm not super experienced w/ calling Scala stuff from Java, but gave it a try and the following seems to work:

```scala
// Given
import enumeratum._

sealed trait MyEnum extends EnumEntry

case object MyEnum extends Enum[MyEnum] {

  val values = findValues

  case object First  extends MyEnum
  case object Second extends MyEnum
  case object Third  extends MyEnum

}
```

The folllowing Java seems to compile fine:

```java
class ExampleUse {
    public static void go() {
        System.out.println(MyEnum$First$.MODULE$);
    }
}
```

Scala: 2.12.4
Enumeratum: 1.5.12

**Comment by martin-g** [comment]
In my case the difference is that MyEnum is inside another `object`.
Finally I was able to resolve it by introducing "factory methods":

```scala
object Transfer {

  sealed trait Type extends EnumEntry

  // the methods are for Java interop
  object Type extends Enum[Type] {
    val values: immutable.IndexedSeq[Type] = findValues

    case object DEPOSIT extends Type
    def deposit(): DEPOSIT.type = DEPOSIT

    case object WITHDRAWAL extends Type
    def withdrawal(): WITHDRAWAL.type = WITHDRAWAL
  }
}
```

and in the Java code I call them with `Transfer.Type$.MODULE$.withdrawal()`

Hope this helps someone else!

Thank you!
