### ISSUE TITLE
Quill integration

### ISSUE THREAD

**Issue by daniel-shuy** [lloydmeta/enumeratum#163]
I have a suggestion to add a trait to automatically encode/decode `EnumEntry`s as `String`s, using their `entryName`, when querying/inserting from/into a Database using [Quill](http://getquill.io).

This is my current implementation:
```scala
import enumeratum.{Enum, EnumEntry}
import io.getquill.MappedEncoding

trait QuillEnum[A <: EnumEntry] {
  this: Enum[A] =>

  implicit lazy val enumEncoder: MappedEncoding[A, String] = MappedEncoding(_.entryName)

  implicit lazy val enumDecoder: MappedEncoding[String, A] = MappedEncoding(withName)
}
```

**Comment by lloydmeta** [comment]
Sounds like a good idea :) A PR for adding said integration is welcome !
