### ISSUE TITLE
Question: Many-to-One Relationships

### ISSUE THREAD

**Issue by neilchaudhuri** [lloydmeta/enumeratum#165]
I am working on an application where multiple, substantively-different strings (*i.e.* not merely differing by casing) can be represented by the same enumeration. The custom code that currently exists accomplishes this by maintaining a `Map[String, Enum]` where values can be duplicated. Callers call methods to retrieve the enum from the map via the string or an "invalidEnum" if no matching key exists in the map.

How could I accomplish this with Enumeratum? I have looked at the README, and it isn't obvious. Any pointers or advice is appreciated.

**Comment by lloydmeta** [comment]
One problem right now is that we have `final val`s for the internal maps of name to values

https://github.com/lloydmeta/enumeratum/blob/9846d57c8fb90c1f9e00f8de69e030ab39fe507b/enumeratum-core/src/main/scala/enumeratum/Enum.scala#L41

If we make those fields on `Enum` and `ValueEnum` non-final I think you'd be able to do this to get this working. You could submit a PR for it if you'd like!

```scala
import enumeratum._

abstract class Number(
  override val entryName: String /* the required default */,
  val otherNames: String *
) extends EnumEntry

case object Number extends Enum[Number] {
  
  case object One   extends Number("one", "1", "eins")
  case object Two   extends Number("two", "2", "zwei")
  case object Three extends Number("three", "3", "drei")
  
  
  val values = findValues

  override val namesToValuesMap: Map[String, Number] =
    values.flatMap { n =>
      (n.entryName -> n) +: n.otherNames.map(name => name -> n)
    }.toMap

}
```

**Comment by neilchaudhuri** [comment]
Thanks for the tip. I will look into it.

**Comment by neilchaudhuri** [comment]
I am ready to submit a PR but don't have permissions. How would you like me to submit it?

**Comment by lloydmeta** [comment]
@neilchaudhuri aaah ok cool; what you need to do is fork this repo, push your local branch up to your fork, and then issue a PR :)

Take a look [here](https://help.github.com/articles/fork-a-repo/) for more info.

**Comment by neilchaudhuri** [comment]
[Done](https://github.com/lloydmeta/enumeratum/pull/175).

**Comment by lloydmeta** [comment]
Done in #175
