### ISSUE TITLE
Missing scala.js artifacts for enumeratum-scalacheck

### ISSUE THREAD

**Issue by nrinaudo** [lloydmeta/enumeratum#166]
There's no real reason not to publish them, all the dependencies are scala.js-compatible. I believe this is just an oversight.

Happy to have a go at a PR on this if you think it's worth it.

**Comment by lloydmeta** [comment]
Ah sorry I should have double-checked in the original PR adding it. I thought it was JVM-only 😅 

PR is definitely more than welcome :)

**Comment by nrinaudo** [comment]
No, the original PR adding scalacheck support didn't include scala.js. The oversight is not yours :)

I've put together a PR (#167). CI is running, and I know from experience it can be tricky with scala.js, but everything seems to work fine locally.

**Comment by nrinaudo** [comment]
Looks like I messed up - looking at oss.sonatype, I can see that `enumeratum-scalacheck` is published under the `enumeratumscalacheck` name. I thought I'd double checked after a local publish, but obviously not well enough.

Should I re-open and submit a corrective PR?

**Comment by nrinaudo** [comment]
PR #168 submitted. Sorry about the mess :/

Technically, you should be able to re-publish under 1.5.13, since no `enumeratum-scalacheck` artifact was ever published for scala.js under version 1.5.13...
