### ISSUE TITLE
Q: Is the "case object" in the circe-enumeratum Usage sample compulsory?

### ISSUE THREAD

**Issue by akauppi** [lloydmeta/enumeratum#174]
https://github.com/lloydmeta/enumeratum#usage-3 has: 

`case object ShirtSize extends Enum[ShirtSize] with CirceEnum[ShirtSize] {
`

Is the `case` there needed for something? My code seems to work without it.

If it's not needed, I would suggest removing it from the sample, since it's just raising eyebrows. (at least for me) 🤨

**Comment by lloydmeta** [comment]
No, it isn't strictly necessary, but it does mean the `.toString` for the object is nice, so we can do have nice error messages:

https://github.com/lloydmeta/enumeratum/blob/c895c327ba48e7646cf8c5815b505efd7d107fd6/enumeratum-circe/src/main/scala/enumeratum/Circe.scala#L42
