### ISSUE TITLE
Worthwhile to Add Doobie Support?

### ISSUE THREAD

**Issue by kevinmeredith** [lloydmeta/enumeratum#186]
Would it be useful to include a `doobie` module within `enumeratum` that provides, `Meta[X]` where `X` is an `Enum` or `EnumEntry`?

I'm just about to write a `Meta` for an `enumeratum._` value, so that made me ask this question!

I'd be interested to work on this, but I wanted to post the question in case you've already implemented or thought about it.

Thanks!

**Comment by lloydmeta** [comment]
Definitely sounds useful to me :) I think such a module might look quite similar to the Quill module, in case that helps.

**Comment by sebastianvoss** [comment]
@kevinmeredith, yes this would be really cool :)

**Comment by lloydmeta** [comment]
Welp, 10 thumbs ups probably means it should be done 😆
