### ISSUE TITLE
How to mix ValueEnumEntry's value with EnumEntry's entryName ?

### ISSUE THREAD

**Issue by zawlazaw** [lloydmeta/enumeratum#198]
Currently, `EnumEntry` allows to override the `entryName`, and `ValueEnumEntry` allows to assign an integer `value` to the entry (e.g., an integer via `IntEnumEntry`). I would like to identify an enum entry by *both* an integer and a name.

By trial and error I found out that this can be achieved by mixing both traits as follows:

	sealed abstract class Loglevel(override val value: Int) extends IntEnumEntry with EnumEntry

	object Loglevel extends IntEnum[Loglevel] with Enum[Loglevel] {

	  import scala.language.experimental.macros
	  override protected def findValues: IndexedSeq[Loglevel] = macro EnumMacros.findValuesImpl[Loglevel]

	  val values = findValues

	  case object Debug extends Loglevel(value = 10)
	  case object Info extends Loglevel(value = 100)
	  case object Warning extends Loglevel(value = 1000)
	}

	object Playground extends App {

	  /*
	   * Everything seems to work fine:
	   */

	  println(Loglevel.withValue(10)) // gives "Debug"
	  println(Loglevel.withNameInsensitive("debug")) // gives "Debug"

	  val ll: Loglevel = Loglevel.Info

	  ll match {
		case Loglevel.Debug => "is debug"
		case Loglevel.Info => "is info"
		case Loglevel.Warning => "is warning"
	  }

	  ll.value match {
		case 10 => "is debug"
		case 100 => "is info"
		case 1000 => "is warning"
		case _ => "is unknown"
	  }
	}

However, since I do not know much about macros, I have no clue whether overriding `findValues` in that way could break something. So, I have two questions:
1. Is it ok (in the sense of "upwards-compatible", and "conflict-free" with Play, Json, etc.) to mix these traits as shown above?
2. Is there an easier way (in the sense of "less boilerplate") to achieve that kind of "`NamedIntEnum`" ?

**Comment by lloydmeta** [comment]
Hmm, to be clear, the two different enum types were not designed to work together; but that isn't to say that things will break; just that you're in uncharted territory.

In concrete terms though, overriding `findValues` / using the macro is not really the issue that I'd be most concerned about though; it would just be the making sure the "normal" scala stuff (methods, values, etc) works as you'd expect.

**Comment by zawlazaw** [comment]
Thanks for clarification.
In the next days I will write a comprehensive test and keep this next to my code in order to check whether  all functionality that I require really works and in order to eventually fail on future versions.
Probably it is not worth to spend time on this use case as a new feature request. In the past I was always fine with enums that are identified by a single id, not two. Here, this requirements comes just from having to be compatible with some proprietary logging system.
So, for me it would be fine to close this issue. If the test is nice and generic, I could hand it in as a PR.

**Comment by lloydmeta** [comment]
> If the test is nice and generic, I could hand it in as a PR.

That'd be awesome @zawlazaw :) Best of luck with your exploration !
