### ISSUE TITLE
publish jars for scala 2.13.0-M5

### ISSUE THREAD

**Issue by pjfanning** [lloydmeta/enumeratum#199]
Would it be possible to publish jars built with scala 2.13.0-M5?

**Comment by lloydmeta** [comment]
It is possible; just needs someone to put the work in 🙂  Would you like to take a stab?

The last time we had a minor version upgrade (2.12), the trick was to publish the integration libs for libs *with* Jars out for the new minor version without having to wait for all of the libs to do so.

The approach I took last time was to keep the main Scala versions as-is

https://github.com/lloydmeta/enumeratum/blob/5e90f627bc220c6f0aecbf5e979e65409f86289a/build.sbt#L4-L8

but then declare a separate aggregation project for the libs that did have support (published jars) for the new minor version

https://github.com/lloydmeta/enumeratum/blob/8a857a98ce429bd37288863f983371af5b17edb1/build.sbt#L56-L80

The idea there would be that we could easily testa and publish all the libs for the new version when support roles out for them by switching to another project (in that case `scala_2_12`).

https://github.com/lloydmeta/enumeratum/blob/469c48e7fd41d78887289cf3e60492c057526a66/.travis.yml#L19-L23

**Comment by jtjeferreira** [comment]
play-json was release for 2.13.0-M5 https://mvnrepository.com/artifact/com.typesafe.play/play-json
