### ISSUE TITLE
sealed abstract class with case objects as Enum values goes into thread wait 

### ISSUE THREAD

**Issue by murugesan70** [lloydmeta/enumeratum#205]
We encountered an issue with enumeratum packages when we use it with sealed abstract class and concrete case objects defined within the Enum Type when running it with Spark. Several of the thread goes into Object.wait() state even though the thread is runnable.

Any help is appreciated or if its fixed with latest code, would like to know.

Thanks,
Murugesan
**Symptoms:**
"Thread-8" #138 prio=5 os_prio=0 tid=0x00007fc5ec015000 nid=0x7147 in Object.wait() [0x00007fc6413cf000]
   java.lang.Thread.State: RUNNABLE
        at SteeringEvent$.<init>(SteeringEvent.scala:8)
        at SteeringEvent$.<clinit>(SteeringEvent.scala)
        at SteeringEvent$Connect$.<init>(SteeringEvent.scala:14)
        at SteeringEvent$Connect$.<clinit>(SteeringEvent.scala)
        at Main$$anon$1.run(Main.scala:15)

"Thread-7" #137 prio=5 os_prio=0 tid=0x00007fc5ec012800 nid=0x7146 in Object.wait() [0x00007fc6414d1000]
   java.lang.Thread.State: RUNNABLE
        at SteeringEvent$Disconnect$.<init>(SteeringEvent.scala:15)
        at SteeringEvent$Disconnect$.<clinit>(SteeringEvent.scala)
        at Main$$anon$1.run(Main.scala:18)

"Thread-6" #136 prio=5 os_prio=0 tid=0x00007fc5ec011000 nid=0x7145 in Object.wait() [0x00007fc6415d2000]
   java.lang.Thread.State: RUNNABLE
        at SteeringEvent$BandSteeringAttempted$.<init>(SteeringEvent.scala:10)
        at SteeringEvent$BandSteeringAttempted$.<clinit>(SteeringEvent.scala)
        at Main$$anon$1.run(Main.scala:16)

"Thread-5" #135 prio=5 os_prio=0 tid=0x00007fc5ec00f000 nid=0x7144 in Object.wait() [0x00007fc6416d3000]
   java.lang.Thread.State: RUNNABLE
        at Main$$anon$1.run(Main.scala:17)

"Thread-4" #134 prio=5 os_prio=0 tid=0x00007fc5ec00e800 nid=0x7143 in Object.wait() [0x00007fc6419d4000]
   java.lang.Thread.State: RUNNABLE
        at SteeringEvent$Probe$.<init>(SteeringEvent.scala:16)
        at SteeringEvent$Probe$.<clinit>(SteeringEvent.scala)
        at Main$$anon$1.run(Main.scala:17)

**Here is a sample code that reproduces:**
Main.scala
```

object Main extends App {
  println("Hello, World!")
  val r = new scala.util.Random
  
  object BSEventType extends Enumeration {
   type BSEventType = Value
   val CONNECT,BAND_STEERING_ATTEMPT,PROBE,DISCONNECT,CLIENT_STEERING_ATTEMPT,CLIENT_BS_BTM,CLIENT_STICKY_BTM,CLIENT_BTM,CLIENT_BS_KICK,CLIENT_STICKY_KICK,CLIENT_BS_BTM_RETRY,CLIENT_STICKY_BTM_RETRY = Value
  } 

  for ( i <- 0 to 1000 ) {
    val thread = new Thread {
      override def run {
        val event = BSEventType(scala.util.Random.nextInt(BSEventType.maxId)) 
        val eventTypeOption = event match {
                case BSEventType.CONNECT => Some(SteeringEvent.Connect)
                case BSEventType.BAND_STEERING_ATTEMPT => Some(SteeringEvent.BandSteeringAttempted)
                case BSEventType.PROBE => Some(SteeringEvent.Probe)
                case BSEventType.DISCONNECT => Some(SteeringEvent.Disconnect)
                case BSEventType.CLIENT_STEERING_ATTEMPT => Some(SteeringEvent.ClientSteeringAttempted)
                case BSEventType.CLIENT_BS_BTM => Some(SteeringEvent.ClientBSBTM)
                case BSEventType.CLIENT_STICKY_BTM => Some(SteeringEvent.ClientStickyBTM)
                case BSEventType.CLIENT_BTM => Some(SteeringEvent.ClientBTM)
                case BSEventType.CLIENT_BS_KICK => Some(SteeringEvent.ClientBSKick)
                case BSEventType.CLIENT_STICKY_KICK => Some(SteeringEvent.ClientStickyKick)
                case BSEventType.CLIENT_BS_BTM_RETRY => Some(SteeringEvent.ClientBSBTMRetry)
                case BSEventType.CLIENT_STICKY_BTM_RETRY => Some(SteeringEvent.ClientStickyBTMRetry)
                case _ => None
        }
        println (eventTypeOption)
      }
    }
    thread.start 
  }
}

```
SteeringEvent.scala
```
import enumeratum._

sealed abstract class SteeringEvent(override val entryName: String, val isBsAttempt: Boolean = false, val isStickyAttempt: Boolean = false) extends EnumEntry {
  def steeringStatsName: String = entryName
}

object SteeringEvent extends Enum[SteeringEvent] {
  val values = findValues

  case object BandSteeringAttempted extends SteeringEvent("bsAttempted", true) {
    override def steeringStatsName: String = "preAssociationBsAttempt"
  }
  case object ClientSteeringAttempted extends SteeringEvent("csAttempted")
  case object Connect extends SteeringEvent("connect")
  case object Disconnect extends SteeringEvent("disconnect")
  case object Probe extends SteeringEvent("probe")
  case object ClientBSBTM extends SteeringEvent("clientBsBTM", true)
  case object ClientStickyBTM extends SteeringEvent("clientStickyBTM", true)
  case object ClientBTM extends SteeringEvent("clientBTM")
  case object ClientBSKick extends SteeringEvent("clientBsKick", true)
  case object ClientStickyKick extends SteeringEvent("clientStickyKick", true, true)
  case object ClientBSBTMRetry extends SteeringEvent("clientBsBTMRetry", true)
  case object ClientStickyBTMRetry extends SteeringEvent("clientStickyBTMRetry", true, true)
}


```

**Comment by lloydmeta** [comment]
Hey there, thanks for raising this.  Just a couple of questions

1. Is this specific to using it with Spark ? You mention this in the description but it isn't in the title, nor is it in the code
2. Have you tried calling `SteeringEvent.values` at the beginning of `Main` anytime before you start kicking off the threads?  If it's an object init issue, it could be some kind of deadlock between the inner object inits and the outer `value` init (which depends on the objects initing);
3. Enumeratum really just boils down to the `findValues` macro, which just expands into an `immutable.Seq(BandSteeringAttempted, ClientSteeringAttempted, ...,  )` at compile time, and asides from that, all the constructs are plain Scala standard features and libs.  Have you tried *not* using enumeratum by writing the `immutable.Seq(...)` yourself, or even not having that `val values` thing, and seeing if it reproduces? Since your code doesn't seem to be using the `values` member at all, you could even go further and do something like

    ```scala
    sealed trait SteeringEvent
    object SteeringEvent {
       case object BandSteeringAttempted extends SteeringEvent
       // etc
    }
    ```
    
    and see if it reproduces. As you go along, you depend less and less on enumeratum, allowing us to figure out (1) if it is an enumeratum problem and (2) if it is, what causes the issues.
4. Given the above, it's probably easier for you to create a cloneable repo :D

Having said all that, I think I know what this is; the classic object init deadlock error, which has nothing to do with Spark or Enumeratum. See [this SO thread](https://stackoverflow.com/questions/15176199/scala-parallel-collection-in-object-initializer-causes-a-program-to-hang) and its accepted answer.

**Comment by lloydmeta** [comment]
Closing this for now due to lack of activity.
