### ISSUE TITLE
Add entryName support to ValueEnum?

### ISSUE THREAD

**Issue by drmontgomery** [lloydmeta/enumeratum#209]
First of all, thank you for a very useful and well-documented library.

As a new user of the library, I was a bit surprised to learn that ValueEnums don't support the various features based on entryName. (e.g. name formatting mixins, withName methods, cached name map, etc.) While it's possible to provide some of this functionality via a custom mixin trait on ValueEnum, it seems a bit odd that moving from Enum to ValueEnum means you give up a bunch of useful features.

Out of curiosity, is there a reason ValueEnumEntry and ValueEnum don't extend EnumEntry and Enum, respectively? This change (along with adding the override modifier to findValues in ValueEnum and its subclasses) seems to work well without any noticeable downsides. The biggest risk I see is possible confusion between withIndex/withValue for numeric ValueEnums and withValue/withName for StringEnum. I'd be happy to submit a pull request with my changes if you're interested.

Again, thanks for the great library.

-David

**Comment by drmontgomery** [comment]
Thanks for the quick response to my question!

Based on your response, I'm not sure my initial post clearly communicated my intent. I definitely appreciate the functionality provided by ValueEnum, and I'm also not suggesting any modifications to the functionality of StringEnum. (i.e. no runtime modification of StringEnum values)

I guess the crux of my point is this: The library (and your post above) seems to say, "ValueEnums should be used only for value-based lookups". As a new user, I was expecting something more like "ValueEnums are Enums that also support unique associated values and value-based lookups."

Basically, the name-based and value-based functionality seem orthogonal. The name-based methods and mix-ins have their uses (otherwise you wouldn't have added them to Enum), and those same uses might also apply to ValueEnums. (e.g. perhaps I need to look up a ValueEnum using its camel-case name, then pass its associated value to another system.)

You are correct that users can roll their own Enum trait that supports both name- and value-based lookups, though it does require calling the corresponding ValueEnumMacros.findValueEntriesImpl macro, which seems a bit like an implementation detail.

Since a similar issue has come up before (#198), and the actual code changes are pretty simple, I figured I'd create an issue to ask.

Regardless, at this point, we've converted all our scala.Enumerations over to Enumeratum, and are very happy.

Thanks again,
-David

**Comment by lloydmeta** [comment]
Sorry this totally slipped my radar again 😅 

I agree that name and value-based functionality are orthogonal, but the (perhaps arbitrary) wall that I want to maintain is that out of the box, `ValueEnum`s should provide the inherent guarantee of compile-time uniqueness on the value you use for lookups.  From what I can tell, having names that are modified at runtime breaks this.

Nonetheless, you're probably right; there might be a use case for wanting to do both, and it can be extrapolated similarly to supporting look ups by multiple values of multiple types, but I just don't really see it being something that is worth supporting out of the box in the general case; it makes a number of things somewhat more difficult to implement (different maps for names, integrations, etc) and possibly teach, neither of which appeal to me.

You brought up #198, but even [there](https://github.com/lloydmeta/enumeratum/issues/198#issuecomment-429238403), it seems to be a niche case. So, as a result, I'll have to respectfully decline this request and close this issue :)
