### ISSUE TITLE
tests fail with Scala PR SNAPSHOT versions

### ISSUE THREAD

**Issue by SethTisue** [lloydmeta/enumeratum#211]
for example if I add https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots as a resolver and then do `++2.12.9-bin-f96c8d2-SNAPSHOT!` followed by `coreJVMTests/test` I get a bunch of failures like

```
[info] ShortEnum withValue
[info] - should return proper members for valid values but throw otherwise *** FAILED ***
[info]   java.lang.RuntimeException: output directory /Users/tisue/enumeratum/macros/.jvm/target/scala-2.12.9-SNAPSHOT/classes does not exist.
[info]   at scala.sys.package$.error(package.scala:30)
[info]   at enumeratum.Eval$.$anonfun$macroToolboxClassPath$1(Eval.scala:25)
[info]   at enumeratum.Eval$.$anonfun$macroToolboxClassPath$1$adapted(Eval.scala:24)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at enumeratum.Eval$.macroToolboxClassPath(Eval.scala:24)
[info]   at enumeratum.Eval$.apply$default$2(Eval.scala:12)
[info]   at enumeratum.values.ValueEnumJVMSpec.$anonfun$testValuesOf$3(ValueEnumJVMSpec.scala:74)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[info]   at enumeratum.values.ValueEnumJVMSpec.$anonfun$testValuesOf$2(ValueEnumJVMSpec.scala:51)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   ...
```

I think it's because the logic in https://github.com/lloydmeta/enumeratum/blob/master/enumeratum-core-jvm-tests/src/test/scala/enumeratum/Eval.scala isn't right for these version numbers

this is a problem in the context of the Scala community build, which we sometimes use to test scala/scala PRs before merging them. for example, we ran into this at https://github.com/scala/scala/pull/7607, but the particular PR doesn't matter.

**Comment by lloydmeta** [comment]
Yeah, you're right, the logic in

https://github.com/lloydmeta/enumeratum/blob/1ba619b64427a09cb7d1b2bee8a8b24d3e671716/enumeratum-core-jvm-tests/src/test/scala/enumeratum/Eval.scala#L30-L40

probably isn't matching and resolving to the right directory for "2.12.9-bin-f96c8d2-SNAPSHOT" versions?

**Comment by SethTisue** [comment]
yeah, looks that way to me.

instead of writing your own logic to locate the directory in question, it might be better to use sbt-buildinfo to have sbt tell the code where the directory is.

**Comment by SethTisue** [comment]
oh, but I see you have a PR correcting the logic, that's fine too, I'll test it later today

**Comment by lloydmeta** [comment]
> yeah, looks that way to me.
> 
> instead of writing your own logic to locate the directory in question, it might be better to use sbt-buildinfo to have sbt tell the code where the directory is.

Brilliant idea.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3986/ shows that the fix worked in the community build, too 👍
