### ISSUE TITLE
KenEncoder and KeyDecoder for CirceEnum

### ISSUE THREAD

**Issue by poslegm** [lloydmeta/enumeratum#221]
`CirceEnum` generates only `Decoder` and `Encoder` for circe. Is there availability to generate also `KeyEncoder` and `KeyDecoder`?

**Comment by lloydmeta** [comment]
Definitely, please feel free to contribute :)

**Comment by poslegm** [comment]
@lloydmeta I just found this PR #219. What restrictions do not allow it to be merged? I can help to resolve it.

FYI @yaroot

**Comment by lloydmeta** [comment]
I’m not exactly sure if it was done! The last part of the description seems to imply more was to come. @yaroot

**Comment by yaroot** [comment]
there's nothing left, could be merged now.

**Comment by lloydmeta** [comment]
Thanks @yaroot and @poslegm I just merged #219 and pushed a new release of `enumeratum-circe` 1.5.21.

**Comment by poslegm** [comment]
Awesome, thank you very much!
