### ISSUE TITLE
Version with scalacheck 1.14?

### ISSUE THREAD

**Issue by nrinaudo** [lloydmeta/enumeratum#226]
Unless I'm mistaken, there's no released version of enumeratum-scalacheck that depends on scalacheck 1.14.x - the latest version is 1.5.15, which depends on scalacheck 1.13.5.

Since scalacheck 1.13.x is not compatible with 1.14.x, this is blocking for projects that want to upgrade it but depend on enumeratum-scalacheck.

It seems that there's already a version of enumeratum-scalacheck ready, it's just not been released? Would it be possible to do so?

**Comment by lloydmeta** [comment]
Ugh, I released 1.5.16 for the change that brought us to 1.14.0 but only released it for 2.13.0-M5. Just released it for the other versions too, thanks for letting me know !
