### ISSUE TITLE
publish additional JARs for 2.13.0?

### ISSUE THREAD

**Issue by pjfanning** [lloydmeta/enumeratum#239]
Some additional projects have published for scala 2.13.0 now.
* play-json (2.7.4)
* play (2.7.3)
* slick (3.3.2)

**Comment by pjfanning** [comment]
play and play-json jars are published but not the slick one

**Comment by AlterEgo7** [comment]
enumeratum-circe still pending

**Comment by lambdista** [comment]
please publish enumeratum-reactivemongo-bson for 2.13 as well

**Comment by AlterEgo7** [comment]
and enumeratum-doobie please

**Comment by lambdista** [comment]
> please publish enumeratum-reactivemongo-bson for 2.13 as well

FYI this has been done as of version 1.5.14 of enumeratum-reactivemongo-bson.

**Comment by itachi3** [comment]
any plans for enumeratum-quill

**Comment by lloydmeta** [comment]
Thanks to @vpavkin for #259 and @gabfssilva for #260, doobie and quill integrations have now been published.  I *think* that's all the modules, for now so I'll close this ticket out. Thanks everyone.
