### ISSUE TITLE
Scala.js 1.0.0 Support

### ISSUE THREAD

**Issue by reibitto** [lloydmeta/enumeratum#272]
Now that Scala.js 1.0.0 is out, it would be nice to get enumeratum published with it. Just taking a quick look, it doesn't look like enumeratum itself has a lot of code migrate, but there are a bunch of library-specific modules (argonaut, play-json, circe, etc.). I'm not sure how you would go about that. Wait for 1.0.0 support on all them? Or stagger the releases?

**Comment by dejvid** [comment]
I would very appreciate build for scala.js 1.0.0.

**Comment by lloydmeta** [comment]
> I'm not sure how you would go about that. Wait for 1.0.0 support on all them? Or stagger the releases?

I think if this is going to happen, the releases should be staggered, starting with releasing macro and core for ScalaJS, and then disabling ScalaJS publishing for the other libs until they release 1.0.0 support :)

I'm fine with just commenting the ScalaJS support for the not-yet-1.0.0 projects.

**Comment by mushtaq** [comment]
Oh, even I am blocked on this one for Scala.js 1.x migration.

**Comment by sbrunk** [comment]
I've taken a stab at updating to Scala.js 1.0 in #276

**Comment by gavares** [comment]
Also eagerly awaiting this. Thanks for the effort @sbrunk
