### ISSUE TITLE
Doobie enums integration seems broken

### ISSUE THREAD

**Issue by FunctorPrototype** [lloydmeta/enumeratum#277]
scala 2.13.1
doobie 0.9.0
enumeratum 1.5.15
enumeratum-doobie 1.5.17
postgresql 12.2

It seems that using enums with doobie is broken, because ```ShirtSize``` example from readme throws 
```"org.postgresql.util.PSQLException: ERROR: column "shirt" is of type shirtsize but expression is of type character varying"```

The only workaround that I've found is
 ```CREATE CAST (character varying AS shirtsize) WITH INOUT AS ASSIGNMENT; ``` 
It does the trick

**Comment by lloydmeta** [comment]
I personally don't use this integration and am not sure what the idiomatic usage here should be.

**Comment by FunctorPrototype** [comment]
I've understood. The problem is that readme example intending usage of varchar column but I use postgres enum column

**Comment by FunctorPrototype** [comment]
I'll create pr to documentation for more clear description of example
