### ISSUE TITLE
PlayInsensitiveJsonEnum: missing implicit compile error

### ISSUE THREAD

**Issue by blanchet4forte** [lloydmeta/enumeratum#279]
Hello,

When I try and use `PlayInsensitiveJsonEnum` I get a missing implicit writer error. When I change back to using `PlayJsonEnum` the compile error goes away.

The only thing I can think of is that `PlayInsensitiveJsonEnum` does not have the `contraJsonWrites` implicit def that `PlayJsonEnum` has.

**Comment by lloydmeta** [comment]
Ah yeah, looks like it was missed in https://github.com/lloydmeta/enumeratum/pull/269.
