### ISSUE TITLE
findValues does not find nested values

### ISSUE THREAD

**Issue by eyalroth** [lloydmeta/enumeratum#284]
Nested enum entries are not found by `findValues`:

```scala
import enumeratum._

sealed trait Greeting extends EnumEntry

object Greeting extends Enum[Greeting] {
  val values = findValues

  case object Hello   extends Greeting
  case object GoodBye extends Greeting
  case object Hi      extends Greeting
  case object Bye     extends Greeting
  
  trait RudeGreeting extends Greeting
  object RudeGreeting {
    case object FuckOff extends RudeGreeting
  }
}

println(Greeting.values)
```

Will only print `Vector(Hello, GoodBye, Hi, Bye)`, leaving out `FuckOff`.

The result is the same even if `FuckOff` extends `Greeting` directly.

**Comment by lloydmeta** [comment]
This was added in 1.6.x thanks to #275

https://scastie.scala-lang.org/lloydmeta/bZ3nTszlS22rdZh8TzXdJw/1

<img width="1735" alt="Screenshot 2020-06-16 at 8 54 52" src="https://user-images.githubusercontent.com/914805/84716793-184c1b80-afaf-11ea-84ca-40a6e9ec44fa.png">

**Comment by eyalroth** [comment]
I guess it's worth updating the Scastie link in the readme :)
