### ISSUE TITLE
Docs say "implement it as case objects", while plain objects seems to work fine

### ISSUE THREAD

**Issue by OndrejSpanel** [lloydmeta/enumeratum#290]
The readme says: "implement it as case objects inside ..."

https://github.com/lloydmeta/enumeratum/blob/2f12f218f803635a82d5026c5e5d44c3a21a4672/README.md#L84-L85

When I have tried it, it seems it is enough to implement it as a plain object. The difference is important when the enum entry itself is a case class, because one cannot inherit case objects from case classes, like in:

```scala
sealed case class E(x: Int) extends EnumEntry

object E extends Enum[E] {
  val values = findValues
  object E1 extends E(1)
  object E2 extends E(2)
}
```

I understand using `case object` seems more natural in most cases, but is there something wrong with the code above? Could the documentation be changed to "implement it as case objects or objects inside..."?

**Comment by lloydmeta** [comment]
Using a `case object` is a recommendation because it causes the objects to have a useful/predictable name for use with the `withName` method. I'd rather leave it as is (more advanced users can use `object`s if they want and bring their own name) to encourage predictability in the 99% use case.

**Comment by OndrejSpanel** [comment]
Perhaps the ScalaDoc for `findValues` could contain some description of what exactly is enumerated? By reading the docs I though perhaps only `case objects` are found.
