### ISSUE TITLE
withName variants that can lookup by enum name with custom entryNames.

### ISSUE THREAD

**Issue by hmemcpy** [lloydmeta/enumeratum#295]
In the readme, there's an example of an enum that uses custom entry names:
```
object State extends Enum[State] {
   ...
   case object Alabama extends State("AL")
   case object Alaska  extends State("AK")
}
```
Which makes it possible to use the overridden name with e.g. `.withName("AL")`.

In my case I need to be able to look up by both the overridden name, as well as the original Enum name, e.g. `.withName("Alabama")`. Unfortunately when overriding this doesn't work - the "original" stable name is lost.

I have defined my own extension `withEnumName` to retrieve it by the original name:

```
  implicit class EnumEntrySyntax[A <: EnumEntry](val e: Enum[A]) extends AnyVal {
    def withEnumName(name: String): A =
      withEnumNameOption(name).getOrElse(
        throw new NoSuchElementException(s"$name is not a member of Enum (${e.values.map(_.toString).mkString(",")})")
      )

    def withEnumNameOption(name: String): Option[A] = e.values.find(_.toString == name)
  }
```

And this works.
My question is: are there existing convenience methods in enumeratum already to look up by the enum name? Otherwise, is this something that could be added? Would be happy to send a PR!

**Comment by lloydmeta** [comment]
Hey there, thanks for checking out this lib. There's way no look up the `.toString` value at the moment *and* use the normal `entryName `, and it doesn't seem like something that I want to support out of the box at the moment, even as an opt-in. My thinking here is that it will likely cause more questions and paths (why not add a 3rd lookup?) than I can and want to support right now (eg. all the different "stack traits" that manipulate names have been a pain).

Thanks again, and I appreciate your understanding.
