### ISSUE TITLE
Do we also support multi-value enums?

### ISSUE THREAD

**Issue by ksceriath** [lloydmeta/enumeratum#299]
Hello,

The readme isn't very explicit about this, so I'm not sure if this is already supported. Is it possible to resolve enum variants from multiple values?

My use case is very similar to the example from the ValueEnum section in readme:
```
sealed abstract class LibraryItem(val value: Int, val name: String) extends IntEnumEntry
object LibraryItem extends IntEnum[LibraryItem] {
  case object Book     extends LibraryItem(value = 1, name = "book")
  ...
}
```
where, we can resolve the variants using `LibraryItem.withValue(1)` method. Is it possible to also resolve it using the `name` field somehow? (Maybe something like `LibraryItem.withName("book")`?)

**Comment by lloydmeta** [comment]
Hey, no, this isn't something that is supported. Adding support for that would be rather non-trivial and not something that I'd be interesting in doing at the moment esp with Scala 3 around the corner, but I think it should be simple enough to add in your own app?

**Comment by ksceriath** [comment]
Yea, sure.. makes sense.
I think we should be able to find a way around this.

Thanks.
