### ISSUE TITLE
enumeratum-play version >= 1.6.1 requires Play 2.8.* (scala 2.12)

### ISSUE THREAD

**Issue by arkangelboss-github** [lloydmeta/enumeratum#312]
Hello,

while upgrading enumeratum-play in a project, I realized that moving from 1.6.0 to 1.6.1 the requirement for play changes from 2.7.* (which is the version used in the project) to 2.8.*, triggering Gradle to apply the requirement.

Is this by design? If it is, can it be documented in the readme?

```
com.beachape:enumeratum-play_2.12:1.6.1
    +--- org.scala-lang:scala-library:2.12.11
    +--- com.beachape:enumeratum-play-json_2.12:1.6.1
    |    +--- org.scala-lang:scala-library:2.12.11
    |    +--- com.typesafe.play:play-json_2.12:2.9.0 (*)
    |    \--- com.beachape:enumeratum_2.12:1.6.1
    |         +--- org.scala-lang:scala-library:2.12.11
    |         \--- com.beachape:enumeratum-macros_2.12:1.6.1
    |              +--- org.scala-lang:scala-library:2.12.11
    |              \--- org.scala-lang:scala-reflect:2.12.11 (*)
    +--- com.typesafe.play:play_2.12:2.8.0 (*)
    \--- com.beachape:enumeratum_2.12:1.6.1 (*)
```

**Comment by lloydmeta** [comment]
Yeah, it's "by design" in so much as I've not tracked the dependency versions in the integration moduel name (the only real way to solve it nicely) and don't intend to. Happy to accept a PR to document this though.

**Comment by arkangelboss-github** [comment]
I understand: I opened https://github.com/lloydmeta/enumeratum/pull/313 to add to the README
