### ISSUE TITLE
findValues empty with nested abstract class enums

### ISSUE THREAD

**Issue by halfmatthalfcat** [lloydmeta/enumeratum#316]
I have a setup like so:

```scala
sealed abstract class MyEnum(override val entryName: String) extends EnumEntry
object MyEnum extends Enum[MyEnum] {
  val values = findValues

  object EnumA {
    case object EnumA1 extends MyEnum("ENUM_A_1")
    case object EnumA2 extends MyEnum("ENUM_A_2")
  }
  
  object EnumB {
    case object EnumB1 extends MyEnum("ENUM_B_1")
    case object EnumB2 extends MyEnum("ENUM_B_2")
  }
}

MyEnum.values = Vector()
```

Why is values empty? Per the docs this _should_ work with a sealed trait but this doesn't work with sealed abstract classes?

**Comment by lloydmeta** [comment]
https://scastie.scala-lang.org/lloydmeta/lsC8tpvqQeCz2ionHVTTYg/1

Works here: 
<img width="1603" alt="Screenshot 2021-05-06 at 10 52 24" src="https://user-images.githubusercontent.com/914805/117230962-28841800-ae59-11eb-8432-f0cf4dfa30ef.png">


Maybe you're using an old version?

**Comment by halfmatthalfcat** [comment]
1. Holy shit, thank you for responding so quickly
2. Yes, I was on 1.5.15 and upgrading to 1.6.1 solved the issue.

Thank you!
