### ISSUE TITLE
add zio-json support

### ISSUE THREAD

**Issue by endertunc** [lloydmeta/enumeratum#317]
I already put some work to add zio-json support but it's always nice to ask; would you be interested in such a PR?

**Comment by lloydmeta** [comment]
Hmm, I myself haven't used ZIO yet (shame, just hadn't had the time), so I wouldn't be a good steward for such an integration. I would recommend that you publish such an integration yourself :)

**Comment by hearnadam** [comment]
> Hmm, I myself haven't used ZIO yet (shame, just hadn't had the time), so I wouldn't be a good steward for such an integration. I would recommend that you publish such an integration yourself :)

Now that zio-json is more mature and popular, I would like to contribute an integration. Assuming it follows the standards set by other integrations, would this be accepted?

**Comment by Not-Aru** [comment]
@lloydmeta just following up on the comment above, would a zio-json integration be accepted?
