### ISSUE TITLE
1.7.1 release is not found in registry

### ISSUE THREAD

**Issue by aleksandr-vin** [lloydmeta/enumeratum#347]
Forgot to publish maybe?

**Comment by lloydmeta** [comment]
Hmm,` 1.7.1` of `enumeratum-quill` does seem to be in Maven Central https://mvnrepository.com/artifact/com.beachape/enumeratum-quill

Please note that integration version are not linked to the "core" version (still at `1.7.0`)

**Comment by aleksandr-vin** [comment]
Top! I missed that last piece of knowledge ;)
