### ISSUE TITLE
Enums with hierarchical structure

### ISSUE THREAD

**Issue by ShahOdin** [lloydmeta/enumeratum#348]
Let's say I have:

```scala
sealed trait Foo
sealed trait FooBar extends Foo
object FooBar{
  case object First extends FooBar
}
sealed trait FooBaz extends Foo
object FooBaz{
  case object First extends FooBaz
}
```

ie, `FooBar.First` and `FooBaz.First` are both examples of my `Foo` enum. The problem is that by default, they both will be serailised as `First` and then the decoding becomes ambigous and I fail to do a round about serailsation. Is there an easy way of adding "scope" to the entry Name of an enum so that I can end up with something like "FooBaz.First" and "FooBar.First" perhaps?

What would be the tidiest way of automatically deriving circe codecs for `Foo`? have asked the question on [gitter](https://gitter.im/lloydmeta/enumeratum?at=62eba40c7ccf6b6d45c65928) too

**Comment by lloydmeta** [comment]
Have you tried playing around with options using `entryName`?

**Comment by ShahOdin** [comment]
Ended up using what I believe is called the stackable trait pattern:

```scala
sealed trait Foo extends EnumEntry
object Foo extends Enum[Foo] with CirceEnum[Foo] {
  sealed trait FooBar extends Foo {
    abstract override def entryName: String = s"FooBar.${super.entryName}"
  }
  object FooBar {
    case object First extends FooBar
  }
  sealed trait FooBaz extends Foo {
    abstract override def entryName: String = s"FooBaz.${super.entryName}"
  }
  object FooBaz {
    case object First extends FooBaz
  }
}
```

which works I guess.
