### ISSUE TITLE
Scala3: findValues fails to compile in nested sealed trait hierarchy

### ISSUE THREAD

**Issue by desavitsky** [lloydmeta/enumeratum#368]
Example: 
```scala
import enumeratum.values.StringEnum
import enumeratum.values.StringEnumEntry

sealed trait FirstLevel extends StringEnumEntry

object FirstLevel extends StringEnum[FirstLevel] {

  case object One extends FirstLevel {
    val value = "one"
  }
  case object Two extends FirstLevel {
    val value = "two"
  }

  sealed trait SecondLevel extends FirstLevel

  case object Three extends SecondLevel {
    val value = "three"
  }

  override def values: IndexedSeq[FirstLevel] = findValues

}
```

https://scastie.scala-lang.org/qpDNUwqAT4m4ovmn4EySgg

Error:
Exception occurred while executing macro expansion.
scala.MatchError: Type.of[...] (of class scala.quoted.runtime.impl.TypeImpl)

**Comment by lloydmeta** [comment]
Interesting... looks like the `collect` method is missing this possible case for `tupleTpe`:

https://github.com/lloydmeta/enumeratum/blob/f9b528ae9e063ae2617a9b8f3232639e48f4763a/macros/src/main/scala-3/enumeratum/ValueEnumMacros.scala#L188-L241
