### ISSUE TITLE
Skinny-orm/scalike-jdbc support

### ISSUE THREAD

**Issue by emanresusername** [lloydmeta/enumeratum#37]
just discovered this project today, and was blown away, i've been looking for something like this for a long time! noticed you mentioned slick support, so figured i'd try to get a [scalike-jdbc](http://scalikejdbc.org/documentation/operations.html)/[skinny-orm](http://skinny-framework.org/documentation/orm.html) story going too. i basically have this
```scala
class Model(specialType: Option[SpecialType]) extends SkinnyRecord[Model]
object Model extends SkinnyCRUDMapper[Model]
sealed trait SpecialType extends EnumEntry

object SpecialType extends CirceEnum[SpecialType] with Enum[SpecialType] {
  val values = findValues

  case object Free extends SpecialType

  case object Beer extends SpecialType

  // cause i'll take FreeBeer over FooBar any day :)

  implicit val specialTypeBinders: Binders[SpecialType] = Binders.string.xmap(
    Option(_).map(SpecialType.withName).orNull,
    _.entryName
  )

  implicit val freeParameterBinderFactory: ParameterBinderFactory[Free.type] = ParameterBinderFactory {
    value => (stmt, idx) => stmt.setString(idx, value.entryName)
  }

  implicit val beerParameterBinderFactory: ParameterBinderFactory[Beer.type] = ParameterBinderFactory {
    value => (stmt, idx) => stmt.setString(idx, value.entryName)
  }
}
```
then i can do scalike-jdbc things like
```scala
Model.findBy(sqls.eq(Model.column.`specialType`, SpectialType.Beer))
```
ideally i'd woudn't need the `freeParameterBinderFactory` and `beerParameterBinderFactory` implicits, but if i take those out, then i have to do
```scala
Model.findBy(sqls.eq(Model.column.`specialType`, SpectialType.Beer.asInstanceOf[SpecialType]))
```
this might be more in scalike-jdbc's court (will raise an issue there too). but in case you know a solution/have a readme update to address it, figured i'd mention it here. 
Most importantly, Thanks million for doing this project!

**Comment by lloydmeta** [comment]
Hey there, I think this is similar to the question I [answered here](https://github.com/lloydmeta/enumeratum/pull/36#issuecomment-221548383) with Slick. In short, the type inferred is the singleton type, which forces you do add those singleton type-mappers.

In these cases, I usually add a type ascription, so:

```scala
Model.findBy(sqls.eq(Model.column.`specialType`, SpectialType.Beer: SpecialType))
```

should work. Can you give that a try?

**Comment by emanresusername** [comment]
^^ super helpful! thanks!

**Comment by lloydmeta** [comment]
Did it work?

**Comment by emanresusername** [comment]
oh yeah, that unblocked me, thanks again
