### ISSUE TITLE
How to upgrade enumeratum-doobie to target v1.0.0-RC4

### ISSUE THREAD

**Issue by sentenza** [lloydmeta/enumeratum#376]
```
[error] 	* org.tpolecat:doobie-core_2.13:1.0.0-RC4 (early-semver) is selected over 1.0.0-RC2
[error] 	    +- org.tpolecat:doobie-h2_2.13:1.0.0-RC4              (depends on 1.0.0-RC4)
[error] 	    +- org.tpolecat:doobie-postgres_2.13:1.0.0-RC4        (depends on 1.0.0-RC4)
[error] 	    +- io.kontainers:common_2.13:1.0                      (depends on 1.0.0-RC4)
[error] 	    +- org.tpolecat:doobie-hikari_2.13:1.0.0-RC4          (depends on 1.0.0-RC4)
[error] 	    +- org.tpolecat:doobie-postgres-circe_2.13:1.0.0-RC4  (depends on 1.0.0-RC4)
[error] 	    +- com.beachape:enumeratum-doobie_2.13:1.7.3          (depends on 1.0.0-RC2)
                                                                                                                 ^^^^^^^^^^^^^^^^^
```

I believe that a new release for `enumeratum-doobie` is needed to include #370

**Comment by sentenza** [comment]
@lloydmeta can you help with that?

**Comment by lloydmeta** [comment]
I think we're already targeting that version?

https://mvnrepository.com/artifact/com.beachape/enumeratum-doobie_3/1.7.4

**Comment by sentenza** [comment]
> I think we're already targeting that version?
> 
> https://mvnrepository.com/artifact/com.beachape/enumeratum-doobie_3/1.7.4

Oh, sorry for that. I was just looking at https://github.com/lloydmeta/enumeratum/tags to check the latest versions of the lib. Probably some tags are missing.

Thank you for your reply.
