### ISSUE TITLE
Scala 3 ValueEnum only finds values if the value constructor parameter is first

### ISSUE THREAD

**Issue by martijnhoekstra** [lloydmeta/enumeratum#396]
```scala
sealed abstract class MyStatus(final val idx: Int, final val value: String) extends StringEnumEntry

object MyStatus extends StringEnum[MyStatus] {
  case object PENDING extends MyStatus(1, "PENDING")
  val values = findValues
}
```

results in

> `Fails to check value entry MyStatus.PENDING for enum MyStatus`

Switching the constructor params fixes the problem.

**Comment by martijnhoekstra** [comment]
I intend to take a quick look myself, hopefully this is relatively easy

**Comment by lloydmeta** [comment]
That _is_ odd.

Would def appreciate your help on this one.

https://github.com/lloydmeta/enumeratum/blob/1fbbd04426480ee99df6f05a03ad54befe124dd9/macros/src/main/scala-3/enumeratum/ValueEnumMacros.scala#L155-L163

^ seems like a relevant area.

**Comment by martijnhoekstra** [comment]
I took a stab at https://github.com/lloydmeta/enumeratum/pull/397, but I find it very difficult to get tests to consistently run locally on scala 3

**Comment by martijnhoekstra** [comment]
https://github.com/lloydmeta/enumeratum/pull/398 should be better.

**Comment by lloydmeta** [comment]
Done via #398
