### ISSUE TITLE
Scala Native 0.5

### ISSUE THREAD

**Issue by MateuszKubuszok** [lloydmeta/enumeratum#401]
Is there a plan to release Enumeratum with Scala Native 0.5?

**Comment by lloydmeta** [comment]
PRs are welcome :)

**Comment by MateuszKubuszok** [comment]
I attempted this in #402

**Comment by luksow** [comment]
@lloydmeta any updates here, regarding issue or @MateuszKubuszok's PR?

**Comment by lloydmeta** [comment]
Nope. For updates, look at the PR itself.

**Comment by luksow** [comment]
@lloydmeta thanks for the reply! Isn't the PR ready? I see checks failed but due to unpublished packages, no?

**Comment by lloydmeta** [comment]
Closed by #403
