### ISSUE TITLE
Doobie 1.0.0-rc6 required

### ISSUE THREAD

**Issue by Dichotomia** [lloydmeta/enumeratum#404]
Hi there,
please update enumeratum-doobie
https://mvnrepository.com/artifact/org.tpolecat/doobie-core_3/1.0.0-RC6

Thank you

**Comment by felix-hedenstrom** [comment]
I have a PR up to add support for this https://github.com/lloydmeta/enumeratum/pull/406

**Comment by lloydmeta** [comment]
Thanks but please see: https://github.com/lloydmeta/enumeratum/pull/406#issuecomment-2363502030
