### ISSUE TITLE
Would be nice with a withName on Value Enums to enable two-way resolving (Read <-> Write)

### ISSUE THREAD

**Issue by jarlah** [lloydmeta/enumeratum#41]
For ex:

``` scala
def withName(name: String): Event = values.find(_.toString == name).getOrElse(throw new NoSuchElementException(s"DNE: $name"))
```

as mentioned in gitter by @lloydmeta 

I will see if I can make some time to find an optimal solution. But if its not assigned to me, just take it if you have a good solution for it.

**Comment by lloydmeta** [comment]
@jarlah is currently working on this.

**Comment by jarlah** [comment]
progress:

added a withName and withNameOpt in ValueEnum trait. But I am not quite sure how usable it will actually be regarding the lack of lowercase mixins etc. For example with a normal enum I can mixin Lowercase but this type is not allowed for value enums. Of course toString will return the actual name of the enum, and I can hard code lowercase check, but then its inconsistent with the other withName function for standard enum type.
