### ISSUE TITLE
Start building against 2.12

### ISSUE THREAD

**Issue by mdedetrich** [lloydmeta/enumeratum#50]
Scala 2.12 is going to come out fairly soon, so its probably a good idea to start building against the latest 2.12 milestone to figure out if there are any potential issues (there shouldn't be any, but who knows)

**Comment by akauppi** [comment]
http://www.scala-lang.org/news/2.12.0

**Comment by lloydmeta** [comment]
@akauppi I've just released the core lib (incl. ScalaJS version), but almost none of the extra integrations are out with their 2.12.0 versions yet.

**Comment by lloydmeta** [comment]
Closing this now. Remaining integration libs should be tracked using #79
