### ISSUE TITLE
2.12 on-going TODOs

### ISSUE THREAD

**Issue by lloydmeta** [lloydmeta/enumeratum#79]
2.12 branch was finally merged, but there are still a few things to look out for 

- Start adding back various integration-related subprojects once they support 2.12
  - [x] Play and Play-JSON: [Ticket](https://github.com/playframework/playframework/issues/6110)
  - [x] ReactiveMongo
  - [x] Argonaut [Ticket](https://github.com/argonaut-io/argonaut/issues/246)
  - [x] Upickle
- [x] Consider adding back Scalafmt again [ticket](https://github.com/olafurpg/scalafmt/issues/485)

**Comment by AndrewZurn** [comment]
Any chance a milestone/rc/snapshot version of enumeratum-play-json built for 2.12 could be published? Might be nice to get out there early (and would also mean a potentially quicker release once play releases 2.6 w/ support for 2.12).

**Comment by lloydmeta** [comment]
@AndrewZurn that's a good point; I've just released 1.5.11-2.6-SNAPSHOT based on the milestone versions for Play and Play-JSON. Once 2.6 is officially released I'll merge https://github.com/lloydmeta/enumeratum/pull/133, removing the suffix.

**Comment by AndrewZurn** [comment]
Awesome, thanks @lloydmeta

**Comment by lloydmeta** [comment]
@AndrewZurn So sorry about that. I forgot to cross build to 2.12. I've just done it and pushed to the Sonatype snapshot repo.

**Comment by lloydmeta** [comment]
Closing now because integrations w/ Play 2.6.0 have been released.
