### ISSUE TITLE
Suggestion: Switch to Immutable collections for findValues

### ISSUE THREAD

**Issue by SattaiLanfear** [lloydmeta/enumeratum#80]
Most applications shouldn't be changing their enumerations mid-execution, but the standard `scala.collection.Seq` implementation doesn't have the immutable guarantees that `scala.colleciton.immutable.Seq` and `immutable.IndexedSeq` provide.

Of course `immutable.Seq` does implement `scala.collection.Seq` allowing backward compatibility, but allowing users to take advantage of the more specific case when useful (a number of libraries are demanding immutable collection parameters).

**Comment by lloydmeta** [comment]
That's actually an excellent idea !

**Comment by SattaiLanfear** [comment]
Wow, fast turnaround.

Thanks!
